
buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}

	dependencies {
		classpath 'org.ajoberstar.grgit:grgit-gradle:4.1.1'
		classpath 'com.bmuschko:gradle-docker-plugin:6.7.0'
		classpath 'org.gradle.playframework:org.gradle.playframework.gradle.plugin:0.14'
	}
}

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import org.gradle.playframework.tasks.TwirlCompile
import org.gradle.playframework.sourcesets.TwirlImports

apply plugin: 'org.ajoberstar.grgit'

def describe = grgit.describe()
if(!hasProperty('latest') && describe && describe.startsWith('v')) {
	version = describe.substring(1)
} else {
	version = 'latest'
}

subprojects {

	version = rootProject.version
	group = 'nl.idgis.downloadtool'
	
	repositories {
		maven {
			url = "https://maven.pkg.github.com/IDgis/sysadmin"
			credentials {
				username = System.getenv("GITHUB_USER") ?: ghUser
				password = System.getenv("GITHUB_TOKEN") ?: ghKey
			}
		}
		maven {
			url = "https://maven.pkg.github.com/IDgis/idgis-commons"
			credentials {
				username = System.getenv("GITHUB_USER") ?: ghUser
				password = System.getenv("GITHUB_TOKEN") ?: ghKey
			}
		}
		mavenCentral()
	}

	tasks.withType(Jar).configureEach {
		manifest {
			attributes("Implementation-Title": project.name)
			project.version ? attributes("Implementation-Version": project.version) : null
		}
	}
}

// java projects
configure([
	project(':dao'),
	project(':domain'),
	project(':queue'),
	project(':downloader')]) {

	apply plugin: 'java-library'

	sourceSets {
		integration {
			java {
				srcDir file('src/integration/java')
			}
			resources.srcDir file('src/integration/resources')
		}
	}

	configurations {
		integrationImplementation {
			extendsFrom implementation, testImplementation
		}
	}

	sourceSets.integration.compileClasspath += sourceSets.main.output + configurations.integrationImplementation
	sourceSets.integration.runtimeClasspath += sourceSets.integration.output + sourceSets.integration.compileClasspath

	tasks.register('integrationTest', Test) {
		group = 'Verification'
		description = 'Runs the integration tests.'
		testClassesDirs = sourceSets.integration.output.classesDirs
		classpath = sourceSets.integration.runtimeClasspath
	}

	dependencies {
		implementation 'org.slf4j:slf4j-api:1.7.14'
		implementation 'org.slf4j:slf4j-log4j12:1.7.14'

		testImplementation 'junit:junit:4.12'
		testImplementation 'org.easymock:easymock:3.4'
	}

}

// play projects
project(':web') {

	apply plugin: 'org.gradle.playframework'
	apply plugin: DockerRemoteConfig

	play {
		platform {
			playVersion = '2.4.6'
			scalaVersion = '2.11'
			javaVersion = JavaVersion.VERSION_1_8
		}
		injectedRoutesGenerator = true
	}

	tasks.withType(TwirlCompile).configureEach {
		defaultImports = TwirlImports.JAVA
	}

	sourceSets.test.resources.srcDir 'test/resources'

	configurations {
		testImplementation.extendsFrom(configurations.play)
		runtimeClasspath.extendsFrom(configurations.play)
	}

	test {
		environment 'PUB_DB_URL', 'jdbc:h2:mem:test'
		environment 'PUB_DB_USER', 'sa'
		environment 'PUB_DB_PW', ''
	}

	repositories {
		maven {
			name "typesafe-maven-release"
			url "https://repo.typesafe.com/typesafe/maven-releases"
		}
		ivy {
			name "typesafe-ivy-release"
			url "https://repo.typesafe.com/typesafe/ivy-releases"
			layout "ivy"
		}
	}

	tasks.register('copyTar', Copy) {
		group = 'Docker'
		dependsOn 'createMainTarDist'
		from { tarTree(tasks.named('createMainTarDist').get().outputs.files.singleFile) }
		into project.layout.buildDirectory.dir('docker')
	}

	tasks.register('createDockerfile', Dockerfile) {
		group = 'Docker'
		dependsOn 'copyTar'
		destFile = project.file('build/docker/Dockerfile')
		from 'azul/zulu-openjdk:8'
		copyFile 'main', '/opt'
		runCommand 'chmod u+x /opt/bin/main'
		exposePort 9000
		defaultCommand '/opt/bin/main'
	}

	tasks.register('buildImage', DockerBuildImage) {
		group = 'Docker'
		dependsOn 'createDockerfile'
		inputDir = project.file('build/docker')
		images = ["idgis/${rootProject.name}_${project.name}:${project.version}".toString()]
	}

	dependencies {
		play 'org.webjars:webjars-play_2.11:2.4.0-2'
		play 'org.webjars:dojo:1.17.2'
		play 'com.typesafe.play:play-java-ws_2.11:2.4.6'
		play 'com.typesafe.play:play-java-jdbc_2.11:2.4.6'

		play project(':domain')
		play project(':dao')
		play project(':queue')
		play 'org.webjars:bootstrap:3.3.6'
		play ("nl.idgis.sys:provisioning-registration:1.1.6-SNAPSHOT") {
			exclude module: "ch.qos.logback"
			exclude module: "logback-classic"
		}

		play 'org.springframework:spring-jdbc:4.2.5.RELEASE'
		play 'com.google.code.gson:gson:2.5'
		play 'com.h2database:h2:2.2.220'
	}
}

// application projects
configure([
	project(':downloader')]) {
	
	apply plugin: 'application'
	apply plugin: DockerRemoteConfig
	
	dependencies {
		implementation project(':dao')
		implementation project(':domain')
		implementation project(':queue')
	}

	tasks.register('copyTar', Copy) {
		group = 'Docker'
		dependsOn distTar
		from tarTree(distTar.archiveFile)
		into project.layout.buildDirectory.dir('docker')
	}

	tasks.register('createDockerfile', Dockerfile) {
		group = 'Docker'
		dependsOn 'copyTar'
		destFile = project.file('build/docker/Dockerfile')
		from 'azul/zulu-openjdk:8'
		copyFile "${project.name}-${project.version}", '/opt'
		runCommand "chmod u+x /opt/bin/${project.name}"
		defaultCommand "/opt/bin/${project.name}"
	}

	tasks.register('buildImage', DockerBuildImage) {
		group = 'Docker'
		dependsOn 'createDockerfile'
		inputDir = project.file('build/docker')
		images = ["idgis/${rootProject.name}_${project.name}:${project.version}".toString()]
	}
}

project(':dao') {
	dependencies {
		implementation project(':domain')
		implementation 'org.postgresql:postgresql:42.7.7'
		implementation 'com.google.code.gson:gson:2.5'
	}
}

project(':queue') {
	dependencies {
		implementation project(':domain')
		implementation 'com.google.code.gson:gson:2.5'
		api 'com.dinstone:beanstalkc:2.2.0'
	}
}

project(':downloader') {

	dependencies {
		implementation 'org.apache.httpcomponents:httpclient:4.5.14'
		implementation 'nl.idgis.commons:commons-cache:0.0.15'
		implementation 'org.springframework:spring-jdbc:5.3.39'
	}

	mainClassName = 'nl.idgis.downloadtool.downloader.DownloadProcessor'
}

defaultTasks 'clean', 'build', 'buildImage'
