beanstalk:
  image: schickling/beanstalkd
  restart: always

downloader:
  image: downloader
  restart: always
  environment:
    BEANSTALK_HOST: beanstalk
    BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
    BEANSTALK_FEEDBACKOK_QUEUE: feedbackOkTube
    BEANSTALK_FEEDBACKERROR_QUEUE: feedbackErrorTube
    ZIP_CACHEPATH: /tmp/cache
  volumes:
    - ./cache:/tmp/cache/
  links:
    - beanstalk

feedback_ok:
  image: feedback
  restart: always
  environment:
    BEANSTALK_HOST: beanstalk
    BEANSTALK_FEEDBACK_QUEUE: feedbackOkTube
    SMTP_HOST: mail.your-server.de
    SMTP_PORT: 25
    DB_USER: postgres
    DB_PW: postgres
    DB_URL: "jdbc:postgresql://db:5432/download"
  links:
    - db
    - beanstalk

feedback_error:
  image: feedback
  restart: always
  environment:
    BEANSTALK_HOST: beanstalk
    BEANSTALK_FEEDBACK_QUEUE: feedbackErrorTube
    SMTP_HOST: mail.your-server.de
    SMTP_PORT: 25
    DB_USER: postgres
    DB_PW: postgres
    DB_URL: "jdbc:postgresql://db:5432/download"
  links:
    - db
    - beanstalk

request:
  image: request
  restart: always
  environment:
    BEANSTALK_HOST: beanstalk
    BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
    DB_USER: postgres
    DB_PW: postgres
    DB_URL: "jdbc:postgresql://db:5432/download"
  links:
    - db
    - beanstalk

db:
  build: db
  expose:
  - "5432"

web:
  image: web
  restart: always
  environment:
    BEANSTALK_HOST: beanstalk
    BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
    METADATA_PREFIX: "http://test-metadata.geodataoverijssel.nl/metadata/dataset/"
    DB_USER: postgres
    DB_PW: postgres
    DB_URL: "jdbc:postgresql://db:5432/download"
    APPLICATION_SECRET: FgZvDqfDukyA9ZmhCBmHTmCoahULjzB4nVzfwFDU7A6wyhNTOHtWN
    ZOOKEEPER_HOST: zookeeper:2181
    SERVICE_DOMAIN_NAME: test.geoportaaloverijssel.nl
    ZIP_CACHEPATH: /tmp/cache
  external_links:
    - base-zookeeper:zookeeper
  links:
    - db
    - beanstalk
  expose:
    - "9000"
  volumes_from:
    - downloader

