version: "2"

services:
  beanstalk:
    image: schickling/beanstalkd
    restart: always

  downloader:
    image: downloader
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
      BEANSTALK_FEEDBACKOK_QUEUE: feedbackOkTube
      BEANSTALK_FEEDBACKERROR_QUEUE: feedbackErrorTube
      ZIP_CACHEPATH : /tmp/cache
    volumes:
    - ./cache:/tmp/cache/
    
  feedback_ok:
    image: feedback
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_FEEDBACK_QUEUE: feedbackOkTube
      SMTP_HOST: mail
      
  feedback_error:
    image: feedback
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_FEEDBACK_QUEUE: feedbackErrorTube
      SMTP_HOST: mail
      
  request:
    image: request
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
