/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rob' at '17-3-16 8:50' with Gradle 2.11
 *
 * @author Rob, @date 17-3-16 8:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
