version: "2"

services:
  beanstalk:
    image: schickling/beanstalkd
    restart: always

  downloader:
    image: downloadtool-downloader
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
      BEANSTALK_FEEDBACKOK_QUEUE: feedbackOkTube
      BEANSTALK_FEEDBACKERROR_QUEUE: feedbackErrorTube
      ZIP_CACHEPATH : /tmp/cache
    volumes:
    - ./cache:/tmp/cache/       
    
  feedbackOK:
    image: downloadtool-feedback
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_FEEDBACK_QUEUE: feedbackOkTube
      SMTP_HOST: mail
      
  feedbackERROR:
    image: downloadtool-feedback
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_FEEDBACK_QUEUE: feedbackErrorTube
      SMTP_HOST: mail
      
  downloadrequest:
    image: downloadtool-downloadrequest
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_DOWNLOAD_QUEUE: downloadRequestTube
  
  mail:
    image: tvial/docker-mailserver
    hostname: solcon.nl
    domainname: idgis.nl
    # your FQDN will be 'mail.domain.com'
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./spamassassin:/tmp/spamassassin/
    - ./postfix:/tmp/postfix/
  